/*-------------------------------------------------------------
sysmets.h -- System metrics display structure
--------------------------------------------------------------*/
#include <Windows.h>

#define NUMLINES ((int) (sizeof sysmetrics / sizeof sysmetrics[0]))
struct 
{
    /* data */
    int iIndex;
    TCHAR * szLabel;
    TCHAR * szDesc;
}
sysmetrics[] =
{
    SM_CXSCREEN,        TEXT("SM_CXSCREEN"),        TEXT("SCREEN WIDTH IN PIXELS"),
    SM_CYSCREEN,        TEXT("SM_CYSCREEN"),        TEXT("SCREEN HEIGHT IN PIXELS"),
    SM_CXVSCROLL,       TEXT("SM_CXVSCROLL"),       TEXT("VERTICAL SCROLL WIDTH"),
    SM_CYHSCROLL,       TEXT("SM_CYSCROLL"),        TEXT("HORIZONTAL SCROLL HEIGHT"),
    SM_CYCAPTION,       TEXT("SM_CYCAPTION"),       TEXT("CAPTION BAR HEIGHT"),
    SM_CXBORDER,        TEXT("SM_CXBORDER"),        TEXT("WINDOW BORDER WIDTH"),
    SM_CYBORDER,        TEXT("SM_CYBORDER"),        TEXT("WINDOW BORDER HEIGHT"),
    SM_CXFIXEDFRAME,    TEXT("SM_FIXEDFRAME"),      TEXT("DIALOG WINDOW FRAME WIDTH"),
    SM_CYFIXEDFRAME,    TEXT("SM_CYFIXEDFRMAE"),    TEXT("DIALOG WINDOW FRAME HEIGHT"),
    SM_CYVTHUMB,        TEXT("SM_CYVTHUMB"),        TEXT("VERTICAL SCROLL THUMB HEIGHT"),
    SM_CXHTHUMB,        TEXT("SM_CXHTHUMB"),        TEXT("HORIZONTAL SCROLL THUMB WIDTH"),
    SM_CXICON,          TEXT("SM_CXICON"),          TEXT("ICON WIDTH"),
    SM_CYICON,          TEXT("SM_CYICON"),          TEXT("ICON HEIGHT"),
    SM_CXCURSOR,        TEXT("SM_CXCURSOR"),        TEXT("CURSOR WIDTH"),
    SM_CYCURSOR,        TEXT("SM_CYCURSOR"),        TEXT("CURSOR HEIGHT"),
    SM_CYMENU,          TEXT("SM_CYMENY"),          TEXT("MENU BAR HEIGHT"),
    SM_CXFULLSCREEN,    TEXT("SM_CXFULLSCREEN"),    TEXT("FULL SCREEN CLIENT AREA WIDTH"),
    SM_CYFULLSCREEN,    TEXT("SM_CYFULLSCREEN"),    TEXT("FULL SCREEN CLIENT AREA HEIGHT"),
    SM_CYKANJIWINDOW,   TEXT("SM_CYKANJIWINDOW"),   TEXT("KANJI WINDOW HEIGHT"),
    SM_MOUSEPRESENT,    TEXT("SM_MOURSEPRESENT"),   TEXT("MOUSE PRESENT FLAG"),
    SM_CYVSCROLL,       TEXT("SM_CYVSCROLL"),       TEXT("VERTICAL SCROLL ARROW HEIGHT"),
    SM_CXVSCROLL,       TEXT("SM_CXVSCROLL"),       TEXT("HORIZONTAL SCROLL ARROW WIDTH"),
    SM_DEBUG,           TEXT("SM_DEBUG"),           TEXT("DEBUG VERSION FLAG"),
    SM_SWAPBUTTON,      TEXT("SM_SWAPBUTTON"),      TEXT("MOUSE BUTTONS SWAPPED FLAG"),
    SM_CXMIN,           TEXT("SM_CXMIN"),           TEXT("MINIMUM WINDOW WIDTH"),
    SM_CYMIN,           TEXT("SM_CYMIN"),           TEXT("MINIMUM WINDOW HEIGHT"),
    SM_CXSIZE,          TEXT("CXSIZE"),             TEXT("MIX/MAX/CLOSE BUTTON WIDTH"),
    SM_CYSIZE,          TEXT("SM_CYSIZE"),          TEXT("MIN/MAX/CLOSE BUTTON HEIGHT"),
    SM_CXSIZEFRAME,     TEXT("SM_CXSIZEFRAME"),     TEXT("WINDOW SIZING FRAME WIDTH"),
    SM_CYSIZEFRAME,     TEXT("SM_CYSIZEFRAME"),     TEXT("WINDOW SIZING FRAME HEIGHT"),
    SM_CXMINTRACK,      TEXT("SM_CXMINTRACK"),      TEXT("MINIMUM WINDOW TRACKING WIDTH"),
    SM_CYMINTRACK,      TEXT("SM_CYMINTRACK"),      TEXT("MINIMUM WINDOW TRACKING HEIGHT"),
    SM_CXDOUBLECLK,     TEXT("SM_CXDOUBLECLK"),     TEXT("DOUBLE CLICK X TOLERANCE"),
    SM_CYDOUBLECLK,     TEXT("SM_CYDOUBLECLK"),     TEXT("DOUBLE CLICK Y TOLERANCE"),
    SM_CXICONSPACING,   TEXT("SM_CXICONSPACING"),   TEXT("HORIZONTAL ICON SPACING"),
    SM_CYICONSPACING,   TEXT("SM_CYICONSPACING"),   TEXT("VERTICAL ICON SPACING"),
    SM_MENUDROPALIGNMENT,TEXT("SM_MENUDROPALIGNMENT"),TEXT("LEFT OR RIGHT MENU DROP"),
    SM_PENWINDOWS,      TEXT("SM_PENWINDOWS"),      TEXT("PEN EXTENSIONS INSTALLAED"),
    SM_DBCSENABLED,     TEXT("DBCSENABLED"),        TEXT("DOUBLE BYTE CHARATER SET ENABLED"),
    SM_CMOUSEBUTTONS,   TEXT("SM_CMOUSEBUTTONS"),   TEXT("NUMBER OF MOUSE BUTTONS"),
    SM_SECURE,          TEXT("SM_SECURE"),          TEXT("SECURITY PRESENT FLAG"),
    SM_CXEDGE,          TEXT("SM_SXEDGE"),          TEXT("3-D BORDER WIDTH"),
    SM_CYEDGE,          TEXT("SM_CYEDGE"),          TEXT("3-D BORDER HEIGHT"),
    SM_CXMINSPACING,    TEXT("SM_CXMINSPACING"),    TEXT("MINIMIXED WINDOW SPACING WIDTH"),
    SM_CYMINSPACING,    TEXT("SM_CYSPACING"),       TEXT("MINIMIZED WINDOW SPACING HEIGHT"),
    SM_CXSMICON,        TEXT("SM_CXSMICON"),        TEXT("SMALL ICON WIDTH"),
    SM_CYSMICON,        TEXT("SM_CYSMICON"),        TEXT("SMALL ICON HEIGHT"),
    SM_CYSMCAPTION,     TEXT("SM_CYSMCAPTION"),     TEXT("SMALL CAPTION HEIGHT"),
    SM_CXSMSIZE,        TEXT("SM_CXSMSIZE"),        TEXT("SMALL CAPTION BUTTON WIDTH"),
    SM_CYSMSIZE,        TEXT("SM_CYSMSIZE"),        TEXT("SMALL CAPTION BUTTON HEIGHT"),
    SM_CXMENUSIZE,      TEXT("SM_CXMENUSIZE"),      TEXT("MENU BAR BUTTON WIDTH"),
    SM_CYMENUSIZE,      TEXT("SM_CYMENUSIZE"),      TEXT("MENU BAR BUTTON HEIGHT"),
    SM_ARRANGE,         TEXT("SM_ARRANGE"),         TEXT("HOW MINIMIZED WINDOWS ARRANGED"),
    SM_CXMINIMIZED,     TEXT("SM_CXMINIMISED"),     TEXT("MINIMIZED WINDOW WIDTH"),
    SM_CYMINIMIZED,     TEXT("SM_CYMINIMIZED"),     TEXT("MINIMIZED WINDOW HEIGHT"),
    SM_CXMAXTRACK,      TEXT("SM_CXMAXTRACK"),      TEXT("MAXIMUM DRAGABLE WIDTH"),
    SM_CYMAXTRACK,      TEXT("SM_CYMAXTRACK"),      TEXT("MAXIMUM DRAGABLE HEIGHT"),
    
};
